# -*- coding: utf-8 -*-
"""大学別 ランキング・定量データ・長所短所（出典は各大学ページ references に記載）"""

ENRICHMENTS = {
    "nagoya-u": {
        "rankings": {"the_japan": "7位", "the_world": "201-250位", "qs_world": "164位（2026）", "qs_japan": "国内6位前後"},
        "stats": {"students": "約1.6万人", "employment_rate": "97%前後（学部）", "grad_school_rate": "40%超（理系は更高）", "tuition_annual": "53.6万円（国立標準）", "deviation": "72-75（理系）"},
        "pros": ["旧帝大ブランドで全国・海外で通じる", "理学・工学の研究設備が国内トップクラス", "トヨタ等東海メーカーとの産学連携が強い", "学費が私立の半額以下"],
        "cons": ["競争が激しく、単位・進級で苦労する学生も", "名古屋以外のキャンパスは理系が集中（東山）", "就活は学内でも争い、早期から準備が必要"],
        "curriculum": "1-2年で基礎科目（数学・物理・化学）→3年から研究室配属。ゼミ・卒研で論文執筆。PBL（問題解決型学習）科目あり。",
        "recognition": "ノーベル賞研究者輩出。経済界「有名企業就職率」ランキングで国立上位。理系院進・研究職・メーカー研究開発で高評価。",
    },
    "kyoto-u": {
        "rankings": {"the_japan": "2-3位", "the_world": "100-150位帯", "qs_world": "50位前後", "qs_japan": "国内2-3位"},
        "stats": {"students": "約2.2万人", "employment_rate": "96%前後", "grad_school_rate": "45%以上", "tuition_annual": "53.6万円", "deviation": "73-76"},
        "pros": ["研究第一の風土、自由度が高い", "理系全分野が揃い院進先も豊富", "iPS細胞等で世界的実績"],
        "cons": ["自律型のためサポートは自分次第", "最難関入試", "京都在住コスト"],
        "curriculum": "フレキシブルカリキュラム。理系は基礎→専門→研究室。院進を前提とした深い学び。",
        "recognition": "旧帝大。学術・研究職で最高評価。メーカー・コンサルも強い。",
    },
    "osaka-u": {
        "rankings": {"the_japan": "4-6位", "the_world": "150-200位帯", "qs_world": "80位前後", "qs_japan": "国内4-5位"},
        "stats": {"employment_rate": "95%前後", "grad_school_rate": "35-40%", "tuition_annual": "53.6万円", "deviation": "70-73"},
        "pros": ["関西圏トップ国立", "基礎工学・工学・理学のバランス", "吹田キャンパスに研究集約"],
        "cons": ["入試難易度が高い", "キャンパス間移動あり"],
        "curriculum": "基礎工学部は融合型カリキュラム。他学部も1-2年基礎→3年専門。",
        "recognition": "旧帝大。関西の製造業・IT就職で最上位クラス。",
    },
    "tohoku-u": {
        "rankings": {"the_japan": "5-8位", "the_world": "200-250位", "qs_world": "100位前後", "qs_japan": "国内5-7位"},
        "stats": {"tuition_annual": "53.6万円", "deviation": "68-72"},
        "pros": ["東北・全国で認知度高い旧帝大", "材料科学・金属材料が強い"],
        "cons": ["仙台での生活", "寒冷地域"],
        "curriculum": "1年次基礎教育→2年次専門。理系は実験・演習比重が大きい。",
        "recognition": "旧帝大。東日本のメーカー・研究機関就職に強い。",
    },
    "kyushu-u": {
        "rankings": {"the_japan": "8-12位", "the_world": "250-350位", "qs_world": "150位前後", "qs_japan": "国内8-10位"},
        "stats": {"tuition_annual": "53.6万円", "deviation": "67-71"},
        "pros": ["九州の最高学府", "工学・医学が強い"],
        "cons": ["福岡以外からの距離"],
        "curriculum": "工学部は学科細分化。実践的演習多め。",
        "recognition": "旧帝大。九州・全国の大企業で高評価。",
    },
    "hokkaido-u": {
        "rankings": {"the_japan": "10-15位", "the_world": "250-400位", "qs_world": "150-200位", "qs_japan": "国内10位前後"},
        "stats": {"tuition_annual": "53.6万円", "deviation": "66-70"},
        "pros": ["広大なキャンパス、自然環境", "低温科学等の特色分野"],
        "cons": ["寒冷・雪", "本州から遠い"],
        "curriculum": "総合入試後に専攻。理系基礎を厚く。",
        "recognition": "旧帝大。全国区就職可能。",
    },
    "tokyo-u": {
        "rankings": {"the_japan": "1位", "the_world": "30-50位", "qs_world": "32位前後", "qs_japan": "国内1位"},
        "stats": {"employment_rate": "98%前後", "grad_school_rate": "50%以上", "tuition_annual": "53.6万円", "deviation": "75-78"},
        "pros": ["国内最高の学術ブランド", "あらゆる分野でトップ研究者", "学費は国立標準"],
        "cons": ["入試最難関", "競争極めて激しい", "東京の生活費"],
        "curriculum": "教養→専門2段階（前期・後期課程）。理系は高度な数学・物理必須。",
        "recognition": "国内最高峰。全世界で認知。",
    },
    "science-tokyo": {
        "rankings": {"the_japan": "15-25位", "the_world": "301-400位", "qs_world": "100位前後（理工）", "qs_japan": "理工系国内トップ"},
        "stats": {"tuition_annual": "53.6万円", "deviation": "72-75"},
        "pros": ["理工系単科国立の最高峰（旧東工大）", "研究・就職ともに理系最難関"],
        "cons": ["理系以外なし", "入試・学習負荷が非常に高い"],
        "curriculum": "1-2年基礎理工、3年からラボ配属。数学・物理・情報が中心。",
        "recognition": "理系就職で東大に次ぐ評価。メーカー・IT・研究職。",
    },
    "tsukuba-u": {
        "rankings": {"the_japan": "20-30位", "the_world": "300-400位", "qs_world": "200-250位", "qs_japan": "国内15-20位"},
        "stats": {"tuition_annual": "53.6万円", "deviation": "65-69"},
        "pros": ["学群制で幅広い理系選択", "研究都市・スタートアップ環境"],
        "cons": ["筑波市の田舎感", "学群選択で迷いやすい"],
        "curriculum": "学群1-2年→学類3-4年。理工学群・情報学群等。",
        "recognition": "国立中堅上位。理系研究・教育職も。",
    },
    "kobe-u": {
        "rankings": {"the_japan": "25-35位", "the_world": "400-600位", "qs_world": "300位前後", "qs_japan": "国内20位前後"},
        "stats": {"tuition_annual": "53.6万円", "deviation": "63-67"},
        "pros": ["関西の中堅国立トップ", "海事・工学に特色"],
        "cons": ["旧帝大より一段下の認知"],
        "curriculum": "融合・複合型カリキュラムを推進。",
        "recognition": "関西圏で安定した評価。",
    },
    "yokohama-nu": {
        "rankings": {"the_japan": "30-40位", "the_world": "401-500位", "qs_japan": "国内25位前後"},
        "stats": {"tuition_annual": "53.6万円", "deviation": "62-66"},
        "pros": ["理工単科、就職率が高い", "横浜・首都圏アクセス"],
        "cons": ["学部数が限定的"],
        "curriculum": "理工学部中心。実践的工学教育。",
        "recognition": "首都圏国立で評価良好。",
    },
    "osaka-metropolitan-u": {
        "rankings": {"the_japan": "30-40位", "the_world": "401-500位", "qs_japan": "国内25位前後"},
        "stats": {"tuition_annual": "53.6万円", "deviation": "62-66"},
        "pros": ["大阪市立+府立統合、学費国立並み", "都市型キャンパス"],
        "cons": ["統合後でブランド整理中"],
        "curriculum": "理学・工学・総合知等。",
        "recognition": "関西の新しい公立大学として認知拡大中。",
    },
    "tus": {
        "rankings": {"the_japan": "40-60位", "the_world": "401-500位", "qs_japan": "私立理工系1位クラス"},
        "stats": {"tuition_annual": "約155-170万円", "deviation": "68-72"},
        "pros": ["私立理工系最高峰", "実学・実験比重が高い", "就職率97%超"],
        "cons": ["学費高い", "入試難易度が高い"],
        "curriculum": "1-2年基礎、3年専門・研究室。実験科目多い。",
        "recognition": "理系就職で最強クラスの私立。",
    },
    "waseda": {
        "rankings": {"the_japan": "20-30位", "the_world": "600-800位", "qs_world": "200位前後", "qs_japan": "私立トップ"},
        "stats": {"tuition_annual": "約150-180万円", "deviation": "66-70"},
        "pros": ["私立総合トップ、ネットワーク", "基幹理工・創造理工が強い"],
        "cons": ["学費高い", "理工は単位取得が大変"],
        "curriculum": "全学教育+専門。国際性高い。",
        "recognition": "民間企業で認知度極めて高い。",
    },
    "keio": {
        "rankings": {"the_japan": "15-25位", "the_world": "500-700位", "qs_world": "200位前後", "qs_japan": "私立トップ"},
        "stats": {"tuition_annual": "約170-200万円", "deviation": "67-71"},
        "pros": ["金融・IT・コンサル就職強い", "理工学部の実践教育"],
        "cons": ["学費最高クラス"],
        "curriculum": "3年から専門深化。英語教育充実。",
        "recognition": "経済界・ITで強いブランド。",
    },
    "nitech": {
        "rankings": {"the_japan": "49位", "the_world": "401-500位（1201-1500帯表記も）", "qs_japan": "国立工科大学系"},
        "stats": {"employment_rate": "98%前後（就職率ランキング常に上位）", "grad_school_rate": "20-25%", "tuition_annual": "53.6万円", "deviation": "62-66"},
        "pros": ["就職率が極めて高い", "学費国立", "愛知にあり地元就職に強い", "実践的工学"],
        "cons": ["大学院進学率は旧帝大より低い（就職志向）", "キャンパス1つ"],
        "curriculum": "高度工学教育課程・創造工学教育課程。長期インターン必須科目あり。",
        "recognition": "「就職率日本一」を争う。中部メーカーから高評価。",
    },
    "gifu-u": {
        "rankings": {"the_japan": "60-80位", "the_world": "1001-1200位", "deviation": "55-58"},
        "stats": {"tuition_annual": "53.6万円", "employment_rate": "90%前後"},
        "pros": ["国立で学費安", "工学・薬学"],
        "cons": ["岐阜の立地", "全国知名度は中程度"],
        "curriculum": "地域国立標準カリキュラム。",
        "recognition": "中部・西日本の中堅。",
    },
    "shizuoka-u": {
        "rankings": {"the_japan": "50-70位", "the_world": "801-1000位", "deviation": "56-59"},
        "stats": {"tuition_annual": "53.6万円"},
        "pros": ["国立、浜松・静岡にキャンパス", "工学・理学"],
        "cons": ["キャンパス分散"],
        "curriculum": "1年基礎→2-4年専門。",
        "recognition": "静岡県内トップ。",
    },
    "aichi-edu": {
        "rankings": {"the_japan": "80-100位", "deviation": "52-55"},
        "stats": {"tuition_annual": "53.6万円", "employment_rate": "95%前後（教員）"},
        "pros": ["教員採用に強い（愛知県）", "学費安"],
        "cons": ["理系就職は教員以外限定的", "教育実習必須"],
        "curriculum": "教科専門+教育科目。",
        "recognition": "愛知の公立教員養成の中心。",
    },
    "meijo-u": {
        "rankings": {"the_japan": "141-150位", "the_world": "1501位以降", "qs_japan": "中堅私大"},
        "stats": {"employment_rate": "95%前後", "tuition_annual": "約140-160万円", "deviation": "52-58（理工）"},
        "pros": ["名古屋で知名度高い", "理工・情報・自動車関連就職", "衣台高校から6名/3年"],
        "cons": ["全国知名度は旧帝大・国立より下", "学費負担"],
        "curriculum": "理工学部は実験・演習中心。自動車関連企業との連携。",
        "recognition": "東海圏の中堅私大トップクラス。地元企業に強い。",
    },
    "chukyo-u": {
        "rankings": {"the_japan": "100-130位", "deviation": "50-54"},
        "stats": {"tuition_annual": "約130-150万円", "employment_rate": "92%前後"},
        "pros": ["名古屋中心、理工学部あり", "衣台実績1名"],
        "cons": ["全国区では弱い"],
        "curriculum": "総合大学型。",
        "recognition": "中京圏の老舗私大。",
    },
    "aichi-u": {
        "rankings": {"the_japan": "100-120位", "deviation": "50-53"},
        "stats": {"tuition_annual": "約120-140万円"},
        "pros": ["名古屋駅近、就職サポート", "データサイエンス等"],
        "cons": ["理工規模は小さめ"],
        "curriculum": "文系強めだが理工も。",
        "recognition": "愛知県内で認知。",
    },
    "nanzan-u": {
        "rankings": {"the_japan": "80-100位", "deviation": "52-56"},
        "stats": {"tuition_annual": "約140-160万円", "employment_rate": "93%前後"},
        "pros": ["カトリック系、リベラルアーツ", "理工学部"],
        "cons": ["学費やや高め"],
        "curriculum": "全人教育+専門。",
        "recognition": "名古屋の有名私大。",
    },
    "dormy-u": {
        "rankings": {"the_japan": "40-60位", "the_world": "801-1000位", "deviation": "58-63"},
        "stats": {"tuition_annual": "約160-180万円"},
        "pros": ["関西トップ私大", "理工・生命医科学"],
        "cons": ["京都生活費", "学費高い"],
        "curriculum": "リベラルアーツ+専門。",
        "recognition": "関西では早慶に次ぐ評価。",
    },
    "ritsumeikan": {
        "rankings": {"the_japan": "40-50位", "the_world": "801-1000位", "deviation": "57-62"},
        "stats": {"tuition_annual": "約160-190万円", "employment_rate": "94%前後"},
        "pros": ["情報理工・理工が強い", "グローバル教育"],
        "cons": ["学費高い", "キャンパス複数"],
        "curriculum": "プロジェクト型学習多い。",
        "recognition": "関西・全国で高い認知。",
    },
    "kansai-u": {
        "rankings": {"the_japan": "50-70位", "deviation": "55-59"},
        "stats": {"tuition_annual": "約130-150万円"},
        "pros": ["化学生命工学等", "関西経済圏就職"],
        "cons": ["理工は学部規模中程度"],
        "curriculum": "総合大学。",
        "recognition": "関西の準難関私大。",
    },
    "tokai-gakuen-u": {
        "rankings": {"the_japan": "150位以降", "deviation": "45-50"},
        "stats": {"tuition_annual": "約110-130万円", "employment_rate": "90%前後"},
        "pros": ["衣台最多14名/3年", "入試方式多様", "地元就職"],
        "cons": ["全国知名度低い", "研究志向には不向き"],
        "curriculum": "実務・資格取得支援。",
        "recognition": "愛知の中堅私大。",
    },
    "aichi-toho-u": {
        "rankings": {"the_japan": "150位以降", "deviation": "44-48"},
        "stats": {"tuition_annual": "約100-120万円"},
        "pros": ["衣台7名/3年", "情報メディア等"],
        "cons": ["偏差値低め"],
        "curriculum": "実践型。",
        "recognition": "愛知東邦は地元就職中心。",
    },
    "ncu": {
        "rankings": {"the_japan": "150位以降", "deviation": "46-50"},
        "stats": {"tuition_annual": "約110-130万円"},
        "pros": ["衣台8名/3年", "経営・情報系"],
        "cons": ["理工系は弱い"],
        "curriculum": "商学中心。",
        "recognition": "名古屋の中堅。",
    },
    "ngu": {
        "rankings": {"the_japan": "150位以降", "deviation": "45-49"},
        "stats": {"tuition_annual": "約110-130万円"},
        "pros": ["衣台2名", "総合私大"],
        "cons": ["理工選択肢少ない"],
        "curriculum": "リベラルアーツ。",
        "recognition": "地元程度。",
    },
    "aichi-gakuin-u": {
        "rankings": {"the_japan": "130-150位", "deviation": "47-51"},
        "stats": {"tuition_annual": "約120-140万円"},
        "pros": ["衣台2名", "心理・健康科学"],
        "cons": ["理系工学はなし"],
        "curriculum": "人文科学系強め。",
        "recognition": "愛知で中堅。",
    },
    "chubu-u": {
        "rankings": {"the_japan": "100-120位", "the_world": "1501+（THE）", "deviation": "50-55"},
        "stats": {"tuition_annual": "約130-150万円", "employment_rate": "91%前後"},
        "pros": ["衣台3名", "理工学部あり", "航空宇宙も"],
        "cons": ["全国区では中程度"],
        "curriculum": "理工は実験多め。",
        "recognition": "中部大学は中部圏で認知。",
    },
    "daido-u": {
        "rankings": {"the_japan": "150位以降", "deviation": "45-49"},
        "stats": {"tuition_annual": "約110-130万円"},
        "pros": ["衣台2名", "工学部（名古屋）"],
        "cons": ["規模小さめ"],
        "curriculum": "工学実践。",
        "recognition": "地元製造業就職。",
    },
    "tokoha-u": {
        "rankings": {"the_japan": "150位以降", "deviation": "44-48"},
        "stats": {"tuition_annual": "約100-120万円"},
        "pros": ["衣台2名", "静岡"],
        "cons": ["理工系限定的"],
        "curriculum": "総合。",
        "recognition": "静岡県内。",
    },
    "aichi-sangyo-u": {
        "rankings": {"the_japan": "150位以降", "deviation": "43-47"},
        "stats": {"tuition_annual": "約100-120万円"},
        "pros": ["衣台3名", "産業大学名の通り企業連携"],
        "cons": ["知名度低い"],
        "curriculum": "実務志向。",
        "recognition": "愛知県内。",
    },
    "aichi-tech-u": {
        "rankings": {"the_japan": "150位以降", "deviation": "44-48"},
        "stats": {"tuition_annual": "約110-130万円"},
        "pros": ["衣台2名", "工学単科"],
        "cons": ["全国知名度低い"],
        "curriculum": "工学中心。",
        "recognition": "地元就職。",
    },
}

# 就職先 年収目安（高卒・製造系中心。出典リンクは shinro-guide 参照欄）
EMPLOYERS = [
    {"name": "トヨタ自動車", "r7": 6, "r6": 6, "r5": 5, "total": 17, "salary_start": "月20.8万円（高卒・2026卒）", "salary_year1": "300-400万円", "salary_30": "550-650万円", "note": "技能職ルート。交替・残業手当で変動大"},
    {"name": "三五", "total": 10, "salary_start": "月18-20万円（製造系目安）", "salary_year1": "280-350万円", "salary_30": "450-550万円", "note": "部品メーカー。地元中堅"},
    {"name": "メイドー", "total": 13, "salary_start": "月18-19万円", "salary_year1": "270-330万円", "salary_30": "400-500万円", "note": "製造・物流系"},
    {"name": "豊田鉄工", "total": 8, "salary_start": "月19-21万円", "salary_year1": "300-380万円", "salary_30": "500-600万円", "note": "トヨタ系部品"},
    {"name": "アイシン", "total": 7, "salary_start": "月20-22万円", "salary_year1": "320-400万円", "salary_30": "550-650万円", "note": "大手部品。待遇やや良"},
    {"name": "デンソー", "total": 2, "salary_start": "月21-23万円", "salary_year1": "350-420万円", "salary_30": "600-700万円", "note": "トヨタ系トップ部品"},
    {"name": "トヨタ車体", "total": 6, "salary_start": "月20-21万円", "salary_year1": "300-380万円", "salary_30": "500-600万円", "note": "トヨタグループ"},
    {"name": "大岡技研", "total": 6, "salary_start": "月17-19万円", "salary_year1": "260-320万円", "salary_30": "400-480万円", "note": "中小製造"},
    {"name": "東郷製作所", "total": 5, "salary_start": "月17-19万円", "salary_year1": "260-320万円", "salary_30": "400-480万円", "note": "部品加工"},
    {"name": "豊田プレス工業", "total": 4, "salary_start": "月19-20万円", "salary_year1": "290-360万円", "salary_30": "480-550万円", "note": "プレス加工"},
]
